baseURL = 'https://wandersoncferreira.github.io'
languageCode = 'en-us'
title = 'Wanderson Ferreira'
subtitle = 'Reifying fragmented ideas'
theme = "nostyleplease"
refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "https://wandersoncferreira.github.io/home/bartuka/code/roam/notes/20240915190218-reference-missing/"
