:PROPERTIES:
:ID:       24e3753d-0209-4988-9a2a-9e59eace502f
:END:
#+TITLE: amplify my strenghts
#+hugo_lastmod: Time-stamp: <2022-05-09 08:43:49 wferreir>

The idea to amplify where you have a good advantage seems interesting but how to
pin point our strengths? I've been battling with this idea for quite some [[id:4417146c-f45e-4181-b346-1e2f3b786f88][time]]
now, my lastest career movement was solely driven by this quest.

In a recent interview process, I had a personality assessment stage where I
discussed with the Head of People all my previous work experiences. In the end
he said I'm an [[id:40bb4e06-4662-40a0-b8f8-e9d36242127a][intrapreneur]] and I kind agree with that. It's very hard to have a
clear [[id:431e95d0-c1eb-4c5a-a64f-65bb344619b0][understanding]] and [[id:79c8ed79-fc93-430a-8dfc-a9a840f6c2c5][guidance]] towards the goal.

These are some of the advices I found online along the way:

#+begin_quote
*Look at your work history, but be careful not to rule out a strength too
 early*. Look at your _rate of improvement_ compared to others with a similar
 level of experience and training, rather than your absolute performance.
#+end_quote

I have a genuine interest for the business behind the things I do as a
programmer. The idea of owning a product and being able to deliver it from start
to finish sounds very good to me. However, there are several roles that one
should take. Looking my career in retrospect there were things I really loved
about the journey and things I hated:

- *understand the business*: loved it
- *make decisions about business direction*: loved it
- *hiring*: terrible because I'm not in charge of the offer
- *technical decisions*: loved it
- *technical trade-offs*: loved it (many bad calls, but I owned it. inevitable learning)
- *providing technical mentorship*: loved it
- *receiving technical mentorship*: loved it when available, terrible when you can't find
- *people management*: hate it, specially delivering news I didn't personally agreed
- *handling uncertainty*: loved it
- *sales pitch*: loved it
- *time pressure/crunch-mode*: loved it (when feasible and not 100% of time)
- *creating solutions out of thin air*: loved it =))
- *internal culture influencer*: loved it
- *team work*: loved it, terrible when you can't get right team structure
- *conflict management*: neutral
- *compromising*: loved it (we can't win every battle)

Compare to others in similar position I was able to identity and active
contribute to each of the points above after starting in a completely new
project.

#+begin_quote
*What doesn't feel like work (but is)?
#+end_quote

Programming / Problem solving.

#+begin_quote
*What unusual combinations can you make?* One useful rule of thumb is to try to combine 2-3 strengths that are not commonly combined.
#+end_quote

I usually get really involved in the business side of the technical things I
work on.

* Long list of skills

I found an interesting [[https://80000hours.org/articles/personal-strengths/][website]] listing a very long list of skills based on
several categories which might be interesting to reference in the future.

However, these are ones I believe I have good fit:

- *active learning*: [[id:431e95d0-c1eb-4c5a-a64f-65bb344619b0][understanding]] the implications of new information for problem solving and decision making
- *critical thinking*: using logic and reasoning to identify the strengths and weaknesses of alternative solutions, conclusions or approaches to problems
- *coordination*: adjusting actions in relation to others' actions
- *instructing*: teaching others how to do something
- *social perceptiveness*: being aware of others' reactions and understanding why they react as they do
- *complex problem solving skills*: identifying complex problems and reviewing related information to develop and evaluate options and implement solutions
- *programming*: writing computer programs for various purposes
- *technology design*: generating or adapting equipment and technology to serve user needs
- *troubleshooting*: determining causes of operating errors and deciding what to do about it
- *judgment and decision making*: considering the relative costs and benefits of potential actions to choose the most appropriate one
- *systems analysis*: determining how a system should work and how changes in conditions, operations, and the environment will affect outcomes
- *systems evaluation*: identifying measures or indicators of system performance and the actions needed to improve or correct performance, relatie to the goals of the system.



* Conclusion / Point of Actions

 From the points given here, seems like [[id:40bb4e06-4662-40a0-b8f8-e9d36242127a][intrapreneurship]] is really something I
 should look more carefully! This raises some questions:

 - how to prepare myself to improve my chances in a new endeavor?
 - clearly the company I work for should foster/promote/reward this behavior. Am I currently in such place?
 - what are well known places where this is a good trait?
