:PROPERTIES:
:ID:       a42bf968-1eb3-422b-a88b-24fa5b4df660
:END:
#+TITLE: fundamentals
#+hugo_lastmod: Time-stamp: <2022-05-21 21:01:07 wferreir>
#+hugo_tags: "advices"

#+begin_quote

Bird must soar. Skunk must stink.\\
Cat must prowl. Man must think.\\

What sets man apart from beast is his engine of\\
thought. His mind. His\\
BRAIN\\
makes him unique\\
and gives his greatest pleasure.\\

But fundamental as is thought for human beings,\\
there is stuff more basic still that underlies and\\
DRIVES\\
not only man\\
but all great beasts,\\

And that is nature's call to each of us... to be special.\\
To be distinguished in some way. To be\\
UNIQUE\\
to BE something, to DO something, BETTER than everyone else.\\

Like the leather nosed chimpanzee,\\
dragging noisy cans and branches,\\
frightning peers into submission,\\

One does not have to be brilliant, a genius, to be special.\\
To do something better than anyone/everyone else. To be\\
UNMATCHED,\\
One has only to choose an END\\
any END\\
that MATTERS\\
that INSPIRES\\
YOU\\
And then DO IT.

- Manuel Blum

#+end_quote
