#+title: How I blog
#+draft: false
#+filetags: meta
#+date: <2022-09-10 Sat> 

This is a meta post in order to teach myself from the future how to do it!

I often spend a few weeks without the desire to write anything in my blog (+I
should fix that but let's be real first+), but at some moment I do want to type
some letters down.. but they I freeze.. how do I do it?

These are the steps I used to write this blog post starting from complete scratch:

1. I use hugo.
2. These are the relevant commands run using Hugo
   
   #+begin_src sh
hugo new site wandersoncferreira
hugo new posts/first.md
cd themes/
git submodule add git@github.com:wandersoncferreira/hugo-theme-nostyleplease.git
   #+end_src
   
3. I use Emacs
4. My Emacs has a ~ox-hugo~ plugin enabled
5. These are the relevant lines to configure ~ox-hugo~ properly
   
   #+begin_src elisp
(after! ox-hugo
  (setq org-hugo-base-dir "~/code/wandersoncferreira.github.io"
        org-hugo-section "posts"))
   #+end_src 
   
6. I wrote an ~org~ file inside the ~orgfiles~ folder
7. I had to add some special meta information in the header of the file:
   1. ~#+title:~
   2. ~#+date:~ created using ~M-x org-time-stamp~
   3. ~#+draft:~ true or false
   4. [OPTIONAL] ~#+author:~
   5. [OPTIONAL] ~#+filetags:~ 
      1. are you wondering why ~filetags~ and not only ~tags~? The [[https://ox-hugo.scripter.co/doc/tags-and-categories/#why-use-plus-filetags-and-not-plus-tags][answer]] is waiting for you
8. Time to publish
   1. ~spc m e~ to run ~org-export-dispatch~
   2. ~H~ to export to ~ox-hugo~
   3. commit all the files

A clever github action will handle everything from here onwards!

