:PROPERTIES:
:ID:       da833eba-fa89-4147-9ca4-a3d246c4a0e7
:END:
#+TITLE: nemawashi
#+hugo_lastmod: Time-stamp: <2022-05-11 06:55:00 wferreir>
#+hugo_tags: "definitions"

Nemawashi (根回し) in Japanese means an informal process of quietly laying the
foundation for some proposed change or project, by talking to the people
concerned, gathering support and feedback, and so forth. It is considered an
important element in any major change, before any formal steps are taken, and
successful nemawashi enables changes to be carried out with the consent of all
sides.

Nemawashi literally translates as "turning the roots", from ne (根, "root") and
mawasu (回す, "to turn something, to put something around something else"). Its
original meaning was literal: in preparation for transplanting a tree, one would
carefully dig around a tree some time before transplanting, and trim the roots
to encourage the growth of smaller roots that will help the tree become
established in its new location.

Nemawashi is often cited as an example of a Japanese word which is difficult to
translate effectively, because it is tied so closely to Japanese culture itself,
although it is often translated as "laying the groundwork."

In Japan, high-ranking people expect to be let in on new proposals prior to an
official meeting. If they find out about something for the first time during the
meeting, they will feel that they have been ignored, and they may reject it for
that reason alone. Thus, it’s important to approach these people individually
before the meeting. This provides an opportunity to introduce the proposal to
them and gauge their reaction. This is also a good chance to hear their input.
This process is referred to as nemawashi.

From [[https://en.wikipedia.org/wiki/Nemawashi][wikipedia]]
