:PROPERTIES:
:ID:       a5d5128a-a16e-4ee6-b62f-75eae369fb79
:END:
#+TITLE: public
#+hugo_lastmod: Time-stamp: <2022-05-22 21:18:05 wferreir>
#+hugo_tags: definition note

I once learned that Kant is extremely precise with the words he chooses to
express any thought. Therefore, everytime I read any Kant essay I need to be
extra diligent with words that I take for granted. This one caught me by
surprise because all of sudden the essay stopped making sense to me. What does
he meant with "public?"

Let's find out! The internet for the rescue. Luckily we have a lot of literature
about everything nowdays. I'm relying on this [[file:~/code/wandersoncferreira.github.io/static/pdfs/laursen1986.pdf][paper]] to make sense of things.

#+begin_quote
[...] The key to his message is his stand on the meaning of the terms "public"
and "private". The private use of reason "is that which a person may make of it
in a particular civil post or office with which he is entrusted", he writes. In
contrast, the public use of reason is a matter of writing and publishing. Kant
explains: "by the public use of one's reason I mean that use which anyone may
make of it as a scholar addressing the entire reading public".
#+end_quote

Seems like he inverted the meaning of public vs private. But why? Seems like a
meaning restriction campaign was held along the years where the term "public"
became associated with "pertaining to the state".
